// Native Android WebView tests on the task's isolated emulator, using public CDP.
import { chromium } from 'playwright-core';
import { execFileSync } from 'node:child_process';
import { mkdirSync, writeFileSync } from 'node:fs';
import assert from 'node:assert/strict';
import path from 'node:path';
import { verifyRadio } from './radio-qa.mjs';
const adbPath=path.join(process.env.ANDROID_HOME,'platform-tools','adb.exe');
const serial=process.env.ANDROID_SERIAL??'emulator-5554';
const adb=(...args)=>execFileSync(adbPath,['-s',serial,...args],{encoding:'utf8',timeout:20000}).trim();
const out='release-artifacts/native';
mkdirSync(out,{recursive:true});
const browser=await chromium.connectOverCDP('http://127.0.0.1:9223',{noDefaults:true});
const context=browser.contexts()[0];
const page=context.pages().find(p=>p.url().includes('appassets.androidplatform.net'))??context.pages()[0];
const errors=[],checks=[],requests=[];
page.on('pageerror',e=>errors.push(e.message));
page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
page.on('request',r=>requests.push(r.url()));
const cdp=await context.newCDPSession(page);
const active=new Map();
const down=async(id,x,y)=>{active.set(id,{id,x,y,radiusX:8,radiusY:8,force:1});await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[...active.values()]});};
const up=async(id)=>{const p=active.get(id);active.delete(id);await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[p]});};
const center=async(selector)=>{const r=await page.locator(selector).first().boundingBox();assert.ok(r,selector);return[r.x+r.width/2,r.y+r.height/2];};
const tap=async(selector)=>{await down(9,...await center(selector));await page.waitForTimeout(70);await up(9);};
const check=(name,detail=true)=>{checks.push({name,detail});console.log(`PASS ${name}`);};
const capture=name=>{const remote=`/sdcard/jokers-qa-${name}.png`;adb('shell','screencap','-p',remote);adb('pull',remote,`${out}/${name}.png`);};
try {
  await page.waitForFunction(()=>window.__joker&&__joker.game.fps>0,null,{timeout:30000});
  const info=await page.evaluate(()=>({ua:navigator.userAgent,size:[innerWidth,innerHeight],dpr:devicePixelRatio,touch:__joker.game.touch.enabled,secure:isSecureContext,orientation:screen.orientation.angle,webgl:!!document.getElementById('gl').getContext('webgl2')}));
  assert.ok(info.touch&&info.secure&&info.webgl);
  check('native WebView loads offline WebGL2 game with touch UI',info);
  capture('01-title');
  await tap('#screen-title [data-privacy]');
  assert.equal(await page.locator('#privacy-dialog').evaluate(el=>el.open),true);
  adb('shell','input','keyevent','4');
  await page.waitForFunction(()=>!document.getElementById('privacy-dialog').open);
  check('actual Android Back dismisses offline privacy dialog');
  await tap('#btn-launch');
  await page.waitForFunction(()=>__joker.game.state==='play');
  await verifyRadio(page,check);
  adb('shell','input','keyevent','4');
  await page.waitForFunction(()=>__joker.game.state==='paused');
  assert.equal(await page.evaluate(()=>__joker.game.audio.voiceSrc),null);
  check('actual Android Back pauses the game');
  await tap('#screen-pause [data-action=resume]');
  await page.waitForFunction(()=>__joker.game.state==='play');
  adb('shell','input','keyevent','3');
  await page.waitForTimeout(800);
  adb('shell','am','start','-n','app.toyboxes.jokersrun/.MainActivity');
  await page.waitForFunction(()=>__joker.game.state==='paused'&&__joker.game.audio.ctx.state==='suspended');
  check('Android Home/background and foreground preserve an explicit paused state');
  capture('02-background-resume');
  await page.evaluate(()=>__joker.start('scouts'));
  await page.waitForTimeout(5000);
  const before=await page.evaluate(()=>({alt:__joker.game.player.pos.y,shots:__joker.game.score.shotsFired}));
  // Use the native CSS viewport, not host coordinates, for the floating stick.
  const size=await page.evaluate(()=>[innerWidth,innerHeight]);
  const startY=Math.min(size[1]-70,280);
  await down(1,130,startY);
  active.set(1,{id:1,x:130,y:startY-55,radiusX:8,radiusY:8,force:1});
  await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[...active.values()]});
  await down(2,...await center('#t-gun'));
  await page.waitForTimeout(900);
  const during=await page.evaluate(()=>__joker.touch());
  assert.ok(during.input.pitch>0.1&&during.input.guns);
  assert.ok(during.shots>before.shots);
  await up(2);await up(1);
  check('native multi-touch flight stick and guns work concurrently',during);
  await tap('#t-boost');
  await page.waitForTimeout(400);
  assert.equal(await page.evaluate(()=>__joker.game.touch.boostLatched),true);
  await down(3,...await center('#t-brake'));
  await page.waitForTimeout(200);
  assert.equal(await page.evaluate(()=>__joker.game.touch.boostLatched),false);
  await up(3);
  check('native boost latch and brake cancel work');
  const vibration=await page.evaluate(()=>({bridge:typeof JokerHaptics.vibrate,vibrate:navigator.vibrate(10)}));
  assert.equal(vibration.bridge,'function');
  check('native haptics bridge installed (physical vibration not judged)',vibration);
  const tilt=await page.evaluate(async()=>{const t=__joker.game.touch.tilt;const enabled=await t.enable();const start=[t.steer,t.pitch];return{enabled,start,api:typeof DeviceOrientationEvent};});
  check('native motion API availability (physical tilt feel untested)',tilt);
  await page.evaluate(()=>__joker.game.touch.tilt.disable());
  capture('03-scout-gameplay');
  const state=await page.evaluate(()=>__joker.state());
  assert.ok(state.fps>0&&state.hp>0);
  check('native gameplay continues without page errors',state);
  assert.deepEqual(errors,[]);
  assert.ok(requests.every(u=>u.startsWith('https://appassets.androidplatform.net/')));
} catch(error) {errors.push(error.stack??String(error));process.exitCode=1;}
finally {
  writeFileSync(`${out}/android-qa.json`,JSON.stringify({environment:'Android16 API36 AOSP x86_64 emulator, Pixel6 profile, hostGPU/WHPX, user-signed debug APK',checks,errors,requests,physicalDeviceTested:false},null,2));
  await browser.close();
}
